name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Step 1: Build and test the application
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOCKEN }}

      # Build backend
      - name: Build Backend Docker Image
        run: docker build -t nahid70/devops-final-backend:latest ./expensy_backend

      # Build frontend
      - name: Build Frontend Docker Image
        run: docker build -t nahid70/devops-final-frontend:latest ./expensy_frontend

      # Push updated images to DockerHub
      - name: Push Backend Docker Image
        run: docker push nahid70/devops-final-backend:latest

      - name: Push Frontend Docker Image
        run: docker push nahid70/devops-final-frontend:latest

      - name: Install Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Test with down and up docker-compose 
      - name: Test Dockerfile images with docker-compose
        run: |
          docker compose -f docker-compose.yaml down
          docker compose -f docker-compose.yaml up -d